config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :destroy]
  resources :posts, except: :index
  resources :users
  resources :likes, only: [:create, :destroy]
  resources :lists, only: [:index, :create, :destroy]
  resources :follows, only: [:create, :destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/search', to: 'search#search'
  get '/users/:id/activity', to: 'users#activity', as: 'user_activity'
  get "*path", to: 'application#redirect_bad_route', constraints: lambda { |req| req.path.exclude? 'rails/active_storage'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :lists, dependent: :destroy

  has_many :follows, dependent: :destroy
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower


  has_many :following_relationships, foreign_key: :user_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  has_one_attached :avatar

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_secure_password

# grabs the most recent posts
  def feed_posts
    Follow.all.select do |follow| follow.follower == self
    end.collect do |follow|
      follow.following.posts.last
    end
  end

  def get_following(current_user)
    Follow.all.find do |follow|
      follow.user_id == current_user.id
      follow.following_id == self.id
    end
  end

  def self.search(search)
    if search
      if User.all.any? {|user| user.username == search || user.name == search}
        User.all.select {|user| (user.username == search || user.name == search)}
      end
    end
  end

  def most_commented_post
    self.posts.max_by {|post| post.comments.length}
  end

  def most_liked_post
    self.posts.max_by {|post| post.likes.length }
  end

  def most_saved_post
    self.posts.max_by {|post| post.lists.length}
  end

  def number_of_following
    self.following.length
  end

  def number_of_followers
    Follow.all.select do |follow|
      follow.following == self
    end.length
  end

  def most_recent_likes
    Like.all.select do |like|
      like.post.user == self
    end.sort_by do |like|
      like.created_at
    end.last(5)
  end

  def most_recent_comments
    Comment.all.select do |comment|
      comment.post.user == self
    end.sort_by do |comment|
      comment.created_at
    end.last(5)
  end

  def most_recent_followers
    Follow.all.select do |follow|
      follow.following == self
    end.sort_by do |follow|
      follow.created_at
    end.last(5)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy, :activity]

  def index
    current_user
    @posts = current_user.feed_posts
  end

  def show
  end

  def new
    if logged_in?
      redirect_to users_path
    else
    @user = User.new
    render :new
    end
  end

  def create
    @user = User.new(user_params)
    placeholder_avatar
    if @user.save
      session[:username] = @user.username
      redirect_to users_path
    else
      render :new
    end
  end

  def activity
    authorized_for_user(@user)
  end

  def edit
    authorized_for_user(@user)
  end

  def update
    @user.update(user_params)
    update_avatar
    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    authorized_for_user(@user)
    @user.destroy
    session.clear
    redirect_to new_user_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :avatar, :bio)
    end

    def require_login
      redirect_to login_path unless session.include? :username
    end

    def find_user
      @user = User.find(params[:id])
    end

    def placeholder_avatar
      if !params[:avatar]
        @user.avatar.attach(io: File.open('app/assets/images/placeholder.png'), filename: 'placeholder.png', content_type: 'image/png')
      end
    end

    def update_avatar
      if params[:avatar]
        @user.avatar.purge
        @user.avatar.attach(params[:avatar])
      end
    end

end

app/views/users/_errors.html.erb
<div class="forms" id="error-flash">
<% if @user.errors %>
  <% @user.errors.full_messages.each do |error| %>
    <div class="ui error message"><%= error %> </div>
  <% end %>
<% end %>
</div>

app/views/users/activity.html.erb
<h2>Recent Activity</h2>
TEST METHODS <br>
User's most commented post: <%= link_to @user.most_commented_post.title, @user.most_commented_post %><br>
User's most liked post: <%= link_to @user.most_liked_post.title, @user.most_liked_post %><br>
User's most saved post: <%= link_to @user.most_saved_post.title, @user.most_saved_post %><br>
Number of Following: <%= @user.number_of_following %><br>
Number of Followers: <%= @user.number_of_followers %><br>
Most commented post: <%= link_to Post.get_most_commented.title, Post.get_most_commented %><br>
Most recent post: <%= link_to Post.get_most_recent.title, Post.get_most_recent %><br>
Random post: <%= link_to Post.get_random.title, Post.get_random %><br>
Most saved post: <%= link_to Post.get_most_saved.title, Post.get_most_saved %><br>
Most liked post: <%= link_to Post.get_most_liked.title, Post.get_most_liked %><br>
<hr>

Most recent liked posts <br>
<% @user.most_recent_likes.each do |like| %>
  <%= link_to like.post.title, like.post %>
<% end %><br>

Most recent comments <br>
<% @user.most_recent_comments.each do |comment| %>
  <%= link_to comment.post.title, comment.post %>
<% end %><br>

Most recent followers <br>
<% @user.most_recent_followers.each do |follow| %>
  <%= link_to follow.follower.username, follow %>
<% end %><br>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>




<body>

  <h2 class="edit-h"> Edit Profile</h2>
  <%= render 'errors' %>

  <div class="ui form" id="edit-form">
    <%= form_for @user do |f| %>
    <div class="two fields">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %><br>
      </div>
      <div class="field">
        <%= f.label :username %>
        <%= f.text_field :username %><br>
      </div>
    </div>
    <div class="two fields">
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %><br>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %><br>
      </div>
    </div>
      <div class="field">
          <%= f.label "Profile Photo" %>
          <%= f.file_field :avatar %><br>
      </div>
      <div class="field">
          <%= f.label "Biography", id: "bio-label" %><br>
          <%= f.text_area :bio %><br>
      </div>
    <div class="ui red big button" >
      <%= f.submit "Update", id: "update-button" %>
    </div>
      <% end %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body id ="body-page">
    <% if @posts.empty? %>
      <%= "No posts yet!" %>
    <% else %>
      <% @posts.each do |post| %>
        <% if post != nil%>
        <div class="ui raised very padded text container segment">
          <%= link_to post.title, post %>
          
        </div>
        <% end %>
      <% end %>
    <% end %>
    <div class="ui right attached rail">
      <div class="ui segment">
        <%= link_to "Saved posts", lists_path %>
      <div class="ui segment">

      </div>
    </div>

</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="edit-h">Sign up</h1>
    <%= render 'errors' %>
    <div class="ui form" id="edit-form">
      <%= form_for @user do |f| %>
      <div class="two fields">
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
          </div>
        </div>
        <div class="two fields">
          <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email %>
          </div>
          <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>
        </div>
        <%= f.hidden_field :bio, value: "Add bio." %>
        <div class="ui red big button">
        <%= f.submit "Submit", id: "update-button" %> </div>
      <% end %>
    </div>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body id="body-page">
  <!-- image -->

  <h1 class="ui block header">
    <% if @user.avatar.attached? %>
      <image src="<%=(url_for(@user.avatar))%>" class="ui medium circular image user_pic">
    <% end %>
    <%= @user.name %>
  </h1>


  <!-- Follow -->
  <% if @user != current_user %>
    <% follow = current_user.follows.find {|follow| follow.following == @user } %>
    <% if follow %>
      <%= form_tag follow_path(follow), method: :delete do %>
      <%=  submit_tag "Unfollow" %>
      <% end %>
    <% else %>
      <%= form_for @user.follows.build do |f| %>
        <%= f.hidden_field :following_id, value: @user.id %>
        <%= f.submit "Follow" %>
      <% end %>
    <% end %>
  <% end %>

  <!-- Followers and Following -->
  <h3>Followers: <%= @user.number_of_followers %>
  <h3>Following: <%= @user.number_of_following %>

<!-- info -->
<h4> <%= @user.bio %> </h4>

<!-- Posts -->

<div class="ui grid three column container">
  <% @user.posts.last(9).each do |post| %>
    <div class="column">
    <% if post %>
      <div class="ui segment large image">
      <div class="ui card">
      <div class="content">
        <div class="left floated meta"><%= post.title %></div>
        <div class="right floated meta"><%= post.format_time%></div>
        <div class="image">
          <% if post.avatar.attached? %>
            <%= link_to (image_tag post.avatar), post %>
          <% else %>
            <br>
            <%= link_to "No attached photo.", post %>
          <% end %>
        </div>
        </div>
        </div>
        <div class="content">
          <span class="right floated">
          <i class="heart outline like icon"></i>
          <%= pluralize(post.likes.length, "Like") %>
          </span>
          <i class="comment icon"></i>
          <%= pluralize(post.comments.length, "Comment") %>
        </div>
        <div class="extra content">
        <div class="ui large transparent left icon input">
        </div>
        </div>
    </div>
    </div>
    <% end %>
  <% end %>
  </div>



  <!-- Edit and delete links -->
  <% if @user == current_user %>
    <%= link_to "Edit profile", edit_user_path %><br>
    <%= link_to "Delete account", user_path(@user), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>

</body>