config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :destroy]
  resources :posts, except: :index
  resources :users
  resources :likes, only: [:create, :destroy]
  resources :lists, only: [:index, :create, :destroy]
  resources :follows, only: [:create, :destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/search', to: 'search#search'
  get '/users/:id/activity', to: 'users#activity', as: 'user_activity'
  get "*path", to: 'application#redirect_bad_route', constraints: lambda { |req| req.path.exclude? 'rails/active_storage'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_one_attached :avatar

  geocoded_by :get_address
  after_validation :geocode

  validates :title, presence: true
  validates :content, presence: true

  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :likes

  def format_time
    self.created_at.strftime("%d %b %Y")
  end

  def get_address
    self.address
  end

  def self.search(search)
    if search != ""
      if Post.all.any? do |post|
        post.title.include?(search) || post.content.include?(search) || post.user.username == search
        end
        Post.all.select {|post| post.title.include?(search) || post.content.include?(search) || post.user.username == search}
      end
    end
  end

  def self.get_most_commented
    Post.all.max_by do |post|
      post.comments.length
    end
  end

  def self.get_most_recent
    Post.all.sort_by do |post|
      post.created_at
    end.last
  end

  def self.get_random
    Post.all.sample
  end

  def self.get_most_saved
    Post.all.max_by do |post|
      post.lists.length
    end
  end

  def self.get_most_liked
    Post.all.max_by do |post|
      post.likes.length
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def show
    if !@post
      redirect_to users_path
    end
  end

  def edit
    authorized_for_user(@post.user)
  end

  def update
    @post.update(post_params)
    update_avatar
    if @post.save
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    authorized_for_user(@post.user)
    @post.destroy
    redirect_to users_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :photo_url, :address, :avatar)
  end

  def require_login
    redirect_to login_path unless session.include? :username
  end

  def find_post
    @post = Post.find_by(id: params[:id])
  end

  def update_avatar
    if params[:avatar]
      @post.avatar.purge
      @post.avatar.attach(params[:avatar])
    end
  end

end

app/views/posts/_errors.html.erb
<div class="forms" id="error-flash">
<% if @post.errors %>
  <% @post.errors.full_messages.each do |error| %>
    <div class="ui error message"><%= error %> </div>
  <% end %>
<% end %>
</div>

app/views/posts/_post_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :photo_url %><br>
  <%= f.text_field :photo_url %><br>
  <%= f.label "Upload photo" %><br>
  <%= f.file_field :avatar, direct_upload: true %><br>
  <%= f.label :address %><br>
  <%= f.text_field :address %><br>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="edit-h">Edit post</h1>
    <%= render 'errors' %>
    <%= render partial: 'post_form', locals: {text: "Update"} %>
  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="edit-h">Create new post</h1>
    <%= render 'errors' %>
    <%= render partial: 'post_form', locals: {text: "Create"} %>
  </body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feed</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body id="body-page">


<!-- Image -->
  <div class="ui vertical stripe segment">
    <div class="row">
      <h1 class="ui header"><%= @post.title %> </h1>
      <span>Posted:<%= @post.format_time %></span>

      <h4>by <%= @post.user.name %></h4>

        <% if @post.avatar.attached? %>
          <%= image_tag @post.avatar, class: "ui medium right floated image"%>
        <% elsif @post.photo_url %>
            <img src="<%= @post.photo_url %>" alt="photo", class="ui medium left floated image">
        <% end %>

        <p><%= @post.content %></p>
        <br>
    </div>

    <div class="row">

        <!-- Like button -->
        <% if @post.user != current_user %>
          <% like = @post.likes.find {|like| like.user == current_user} %>
          <% if like %>
            <%= form_tag like_path(like), method: :delete do %>
            <%=  submit_tag "Unlike" %>
            <% end %>
          <% else %>
            <%= form_for @post.likes.build do |f| %>
              <%= f.hidden_field :post_id %>
              <%= f.submit "Like" %>
            <% end %>
          <% end %>

        <!-- Save button  -->
          <% list = @post.lists.find {|list| list.user == current_user} %>
          <% if list %>
            <%= form_tag list_path(list), method: :delete do %>
            <%=  submit_tag "Unsave" %>
            <% end %>
          <% else %>
            <%= form_for @post.lists.build do |f| %>
              <%= f.hidden_field :post_id %>
              <%= f.submit "Save" %>
            <% end %>
          <% end %>
        <% end %>

        <!-- Links to edit and delete -->
        <% if @post.user == current_user %>
          <%= link_to "Edit", edit_post_path(@post) %><br>
          <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>

        <!-- Comments -->
        <ul>
        <% @post.comments.each do |comment| %>
          <li><%= comment.user.name + ": " + comment.content %></li>
        <% end %>
        </ul>
        <br>

        <!-- Comments form -->
        <%= form_for @post.comments.build do |f| %>
          <%= f.label :content, "Comment:" %><br>
          <%= f.text_area :content %>
          <%= f.hidden_field :post_id %><br>
          <%= f.submit %>
        <% end %>
        <br>
      </div>


      <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
      <script src='https://api.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
      <link href='https://api.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css' rel='stylesheet' />
      <style>
        body { margin:10px; padding:0; }
        #map { position:static; top:0; bottom:0; width:100%; }
      </style>
      <div id='map' style='width: 400px; height: 300px;'>
        <script>
          mapboxgl.accessToken = '<%= ENV['API_TOKEN'] %>'
          if (!mapboxgl.supported()) {
            alert('Your browser does not support Mapbox GL');
          } else {
            var map = new mapboxgl.Map({
              container: 'map',
              style: 'mapbox://styles/mapbox/streets-v9',
              center: [<%= @post.longitude %>, <%= @post.latitude %>],
              zoom: 15
            });
          }
        </script>
      </div>
    </div>


</body>
</html>