config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :destroy]
  resources :posts, except: :index
  resources :users
  resources :likes, only: [:create, :destroy]
  resources :lists, only: [:index, :create, :destroy]
  resources :follows, only: [:create, :destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/search', to: 'search#search'
  get '/users/:id/activity', to: 'users#activity', as: 'user_activity'
  get "*path", to: 'application#redirect_bad_route', constraints: lambda { |req| req.path.exclude? 'rails/active_storage'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="body-page">

    <% if current_user %>
    <div class="ui inverted top fixed menu">
      <div class="left menu">

          <span class="item"> Welcome <%= current_user.name %> </span>

      </div>
      <div class="right menu">
        <%= link_to "Home", users_path, class: "green item" %>
        <%= link_to "Profile", current_user, class: "green item" %>
        <%= link_to "Activity", user_activity_path(current_user), class: "green item" %>
        <%= link_to "New post", new_post_path, class: "green item" %>
        <% if !current_user.blank? %>
          <%= link_to "Logout", logout_path, class: "green item", method: "DELETE" %>
        <% else %>
          <%= link_to "Login", login_path, class: "green item" %>
        <% end %>

        <div class="item">
          <%= form_tag search_path, method: "get", class: "ui transparent inverted left icon input" do  %>
          <i class="search icon"></i>
            <%= text_field_tag :search %>
            <%= submit_tag "Search", placeholder: 'Enter search term...', class: "ui button" %>
          <% end %>
        </div>

      </div>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>